import { Injectable } from '@angular/core';
import { CityI, StateI } from '../models/location.interface';

@Injectable()
export class DataService {
    private states: StateI[] = [
        { id: 5, name: ' ANTIOQUIA ' },
        { id: 8, name: ' ATLANTICO ' },
        { id: 11, name: ' BOGOTA ' },
        { id: 13, name: ' BOLIVAR ' },
        { id: 15, name: ' BOYACA ' },
        { id: 17, name: ' CALDAS ' },
        { id: 18, name: ' CAQUETA ' },
        { id: 19, name: ' CAUCA ' },
        { id: 20, name: ' CESAR ' },
        { id: 23, name: ' CORDOBA ' },
        { id: 25, name: ' CUNDINAMARCA ' },
        { id: 27, name: ' CHOCO ' },
        { id: 41, name: ' HUILA ' },
        { id: 44, name: ' LA GUAJIRA ' },
        { id: 47, name: ' MAGDALENA ' },
        { id: 50, name: ' META ' },
        { id: 52, name: ' NARIÑO ' },
        { id: 54, name: ' N. DE SANTANDER ' },
        { id: 63, name: ' QUINDIO ' },
        { id: 66, name: ' RISARALDA ' },
        { id: 68, name: ' SANTANDER ' },
        { id: 70, name: ' SUCRE ' },
        { id: 73, name: ' TOLIMA ' },
        { id: 76, name: ' VALLE DEL CAUCA ' },
        { id: 81, name: ' ARAUCA ' },
        { id: 85, name: ' CASANARE ' },
        { id: 86, name: ' PUTUMAYO ' },
        { id: 88, name: ' SAN ANDRES ' },
        { id: 91, name: ' AMAZONAS ' },
        { id: 94, name: ' GUAINIA ' },
        { id: 95, name: ' GUAVIARE ' },
        { id: 97, name: ' VAUPES ' },
        { id: 99, name: ' VICHADA ' },
    ];

    private cities: CityI[] = [
        { id: 1, countryId: 5, name: ' MEDELLIN ' },
        { id: 2, countryId: 5, name: ' ABEJORRAL ' },
        { id: 4, countryId: 5, name: ' ABRIAQUI ' },
        { id: 21, countryId: 5, name: ' ALEJANDRIA ' },
        { id: 30, countryId: 5, name: ' AMAGA ' },
        { id: 31, countryId: 5, name: ' AMALFI ' },
        { id: 34, countryId: 5, name: ' ANDES ' },
        { id: 36, countryId: 5, name: ' ANGELOPOLIS ' },
        { id: 38, countryId: 5, name: ' ANGOSTURA ' },
        { id: 40, countryId: 5, name: ' ANORI ' },
        { id: 42, countryId: 5, name: ' SANTAFE DE ANTIOQUIA ' },
        { id: 44, countryId: 5, name: ' ANZA ' },
        { id: 45, countryId: 5, name: ' APARTADO ' },
        { id: 51, countryId: 5, name: ' ARBOLETES ' },
        { id: 55, countryId: 5, name: ' ARGELIA ' },
        { id: 59, countryId: 5, name: ' ARMENIA ' },
        { id: 79, countryId: 5, name: ' BARBOSA ' },
        { id: 86, countryId: 5, name: ' BELMIRA ' },
        { id: 88, countryId: 5, name: ' BELLO ' },
        { id: 91, countryId: 5, name: ' BETANIA ' },
        { id: 93, countryId: 5, name: ' BETULIA ' },
        { id: 101, countryId: 5, name: ' CIUDAD BOLIVAR ' },
        { id: 107, countryId: 5, name: ' BRICEÑO ' },
        { id: 113, countryId: 5, name: ' BURITICA ' },
        { id: 120, countryId: 5, name: ' CACERES ' },
        { id: 125, countryId: 5, name: ' CAICEDO ' },
        { id: 129, countryId: 5, name: ' CALDAS ' },
        { id: 134, countryId: 5, name: ' CAMPAMENTO ' },
        { id: 138, countryId: 5, name: ' CAÑASGORDAS ' },
        { id: 142, countryId: 5, name: ' CARACOLI ' },
        { id: 145, countryId: 5, name: ' CARAMANTA ' },
        { id: 147, countryId: 5, name: ' CAREPA ' },
        { id: 148, countryId: 5, name: ' EL CARMEN DE VIBORAL ' },
        { id: 150, countryId: 5, name: ' CAROLINA ' },
        { id: 154, countryId: 5, name: ' CAUCASIA ' },
        { id: 172, countryId: 5, name: ' CHIGORODO ' },
        { id: 190, countryId: 5, name: ' CISNEROS ' },
        { id: 197, countryId: 5, name: ' COCORNA ' },
        { id: 206, countryId: 5, name: ' CONCEPCION ' },
        { id: 209, countryId: 5, name: ' CONCORDIA ' },
        { id: 212, countryId: 5, name: ' COPACABANA ' },
        { id: 234, countryId: 5, name: ' DABEIBA ' },
        { id: 237, countryId: 5, name: ' DON MATIAS ' },
        { id: 240, countryId: 5, name: ' EBEJICO ' },
        { id: 250, countryId: 5, name: ' EL BAGRE ' },
        { id: 264, countryId: 5, name: ' ENTRERRIOS ' },
        { id: 266, countryId: 5, name: ' ENVIGADO ' },
        { id: 282, countryId: 5, name: ' FREDONIA ' },
        { id: 284, countryId: 5, name: ' FRONTINO ' },
        { id: 306, countryId: 5, name: ' GIRALDO ' },
        { id: 308, countryId: 5, name: ' GIRARDOTA ' },
        { id: 310, countryId: 5, name: ' GOMEZ PLATA ' },
        { id: 313, countryId: 5, name: ' GRANADA ' },
        { id: 315, countryId: 5, name: ' GUADALUPE ' },
        { id: 318, countryId: 5, name: ' GUARNE ' },
        { id: 321, countryId: 5, name: ' GUATAPE ' },
        { id: 347, countryId: 5, name: ' HELICONIA ' },
        { id: 353, countryId: 5, name: ' HISPANIA ' },
        { id: 360, countryId: 5, name: ' ITAGUI ' },
        { id: 361, countryId: 5, name: ' ITUANGO ' },
        { id: 364, countryId: 5, name: ' JARDIN ' },
        { id: 368, countryId: 5, name: ' JERICO ' },
        { id: 376, countryId: 5, name: ' LA CEJA ' },
        { id: 380, countryId: 5, name: ' LA ESTRELLA ' },
        { id: 390, countryId: 5, name: ' LA PINTADA ' },
        { id: 400, countryId: 5, name: ' LA UNION ' },
        { id: 411, countryId: 5, name: ' LIBORINA ' },
        { id: 425, countryId: 5, name: ' MACEO ' },
        { id: 440, countryId: 5, name: ' MARINILLA ' },
        { id: 467, countryId: 5, name: ' MONTEBELLO ' },
        { id: 475, countryId: 5, name: ' MURINDO ' },
        { id: 480, countryId: 5, name: ' MUTATA ' },
        { id: 483, countryId: 5, name: ' NARIÑO ' },
        { id: 490, countryId: 5, name: ' NECOCLI ' },
        { id: 495, countryId: 5, name: ' NECHI ' },
        { id: 501, countryId: 5, name: ' OLAYA ' },
        { id: 541, countryId: 5, name: ' PEÐOL ' },
        { id: 543, countryId: 5, name: ' PEQUE ' },
        { id: 576, countryId: 5, name: ' PUEBLORRICO ' },
        { id: 579, countryId: 5, name: ' PUERTO BERRIO ' },
        { id: 585, countryId: 5, name: ' PUERTO NARE ' },
        { id: 591, countryId: 5, name: ' PUERTO TRIUNFO ' },
        { id: 604, countryId: 5, name: ' REMEDIOS ' },
        { id: 607, countryId: 5, name: ' RETIRO ' },
        { id: 615, countryId: 5, name: ' RIONEGRO ' },
        { id: 628, countryId: 5, name: ' SABANALARGA ' },
        { id: 631, countryId: 5, name: ' SABANETA ' },
        { id: 642, countryId: 5, name: ' SALGAR ' },
        { id: 647, countryId: 5, name: ' SAN ANDRES DE CUERQUIA ' },
        { id: 649, countryId: 5, name: ' SAN CARLOS ' },
        { id: 652, countryId: 5, name: ' SAN FRANCISCO ' },
        { id: 656, countryId: 5, name: ' SAN JERONIMO ' },
        { id: 658, countryId: 5, name: ' SAN JOSE DE LA MONTAÑA ' },
        { id: 659, countryId: 5, name: ' SAN JUAN DE URABA ' },
        { id: 660, countryId: 5, name: ' SAN LUIS ' },
        { id: 664, countryId: 5, name: ' SAN PEDRO ' },
        { id: 665, countryId: 5, name: ' SAN PEDRO DE URABA ' },
        { id: 667, countryId: 5, name: ' SAN RAFAEL ' },
        { id: 670, countryId: 5, name: ' SAN ROQUE ' },
        { id: 674, countryId: 5, name: ' SAN VICENTE ' },
        { id: 679, countryId: 5, name: ' SANTA BARBARA ' },
        { id: 686, countryId: 5, name: ' SANTA ROSA DE OSOS ' },
        { id: 690, countryId: 5, name: ' SANTO DOMINGO ' },
        { id: 697, countryId: 5, name: ' EL SANTUARIO ' },
        { id: 736, countryId: 5, name: ' SEGOVIA ' },
        { id: 756, countryId: 5, name: ' SONSON ' },
        { id: 761, countryId: 5, name: ' SOPETRAN ' },
        { id: 789, countryId: 5, name: ' TAMESIS ' },
        { id: 790, countryId: 5, name: ' TARAZA ' },
        { id: 792, countryId: 5, name: ' TARSO ' },
        { id: 809, countryId: 5, name: ' TITIRIBI ' },
        { id: 819, countryId: 5, name: ' TOLEDO ' },
        { id: 837, countryId: 5, name: ' TURBO ' },
        { id: 842, countryId: 5, name: ' URAMITA ' },
        { id: 847, countryId: 5, name: ' URRAO ' },
        { id: 854, countryId: 5, name: ' VALDIVIA ' },
        { id: 856, countryId: 5, name: ' VALPARAISO ' },
        { id: 858, countryId: 5, name: ' VEGACHI ' },
        { id: 861, countryId: 5, name: ' VENECIA ' },
        { id: 873, countryId: 5, name: ' VIGIA DEL FUERTE ' },
        { id: 885, countryId: 5, name: ' YALI ' },
        { id: 887, countryId: 5, name: ' YARUMAL ' },
        { id: 890, countryId: 5, name: ' YOLOMBO ' },
        { id: 893, countryId: 5, name: ' YONDO ' },
        { id: 895, countryId: 5, name: ' ZARAGOZA ' },
        { id: 1, countryId: 8, name: ' BARRANQUILLA ' },
        { id: 78, countryId: 8, name: ' BARANOA ' },
        { id: 137, countryId: 8, name: ' CAMPO DE LA CRUZ ' },
        { id: 141, countryId: 8, name: ' CANDELARIA ' },
        { id: 296, countryId: 8, name: ' GALAPA ' },
        { id: 372, countryId: 8, name: ' JUAN DE ACOSTA ' },
        { id: 421, countryId: 8, name: ' LURUACO ' },
        { id: 433, countryId: 8, name: ' MALAMBO ' },
        { id: 436, countryId: 8, name: ' MANATI ' },
        { id: 520, countryId: 8, name: ' PALMAR DE VARELA ' },
        { id: 549, countryId: 8, name: ' PIOJO ' },
        { id: 558, countryId: 8, name: ' POLONUEVO ' },
        { id: 560, countryId: 8, name: ' PONEDERA ' },
        { id: 573, countryId: 8, name: ' PUERTO COLOMBIA ' },
        { id: 606, countryId: 8, name: ' REPELON ' },
        { id: 634, countryId: 8, name: ' SABANAGRANDE ' },
        { id: 638, countryId: 8, name: ' SABANALARGA ' },
        { id: 675, countryId: 8, name: ' SANTA LUCIA ' },
        { id: 685, countryId: 8, name: ' SANTO TOMAS ' },
        { id: 758, countryId: 8, name: ' SOLEDAD ' },
        { id: 770, countryId: 8, name: ' SUAN ' },
        { id: 832, countryId: 8, name: ' TUBARA ' },
        { id: 849, countryId: 8, name: ' USIACURI ' },
        { id: 1, countryId: 11, name: ' BOGOTA, D.C. ' },
        { id: 1, countryId: 13, name: ' CARTAGENA ' },
        { id: 6, countryId: 13, name: ' ACHI ' },
        { id: 30, countryId: 13, name: ' ALTOS DEL ROSARIO ' },
        { id: 42, countryId: 13, name: ' ARENAL ' },
        { id: 52, countryId: 13, name: ' ARJONA ' },
        { id: 62, countryId: 13, name: ' ARROYOHONDO ' },
        { id: 74, countryId: 13, name: ' BARRANCO DE LOBA ' },
        { id: 140, countryId: 13, name: ' CALAMAR ' },
        { id: 160, countryId: 13, name: ' CANTAGALLO ' },
        { id: 188, countryId: 13, name: ' CICUCO ' },
        { id: 212, countryId: 13, name: ' CORDOBA ' },
        { id: 222, countryId: 13, name: ' CLEMENCIA ' },
        { id: 244, countryId: 13, name: ' EL CARMEN DE BOLIVAR ' },
        { id: 248, countryId: 13, name: ' EL GUAMO ' },
        { id: 268, countryId: 13, name: ' EL PEÑON ' },
        { id: 300, countryId: 13, name: ' HATILLO DE LOBA ' },
        { id: 430, countryId: 13, name: ' MAGANGUE ' },
        { id: 433, countryId: 13, name: ' MAHATES ' },
        { id: 440, countryId: 13, name: ' MARGARITA ' },
        { id: 442, countryId: 13, name: ' MARIA LA BAJA ' },
        { id: 458, countryId: 13, name: ' MONTECRISTO ' },
        { id: 468, countryId: 13, name: ' MOMPOS ' },
        { id: 490, countryId: 13, name: ' NOROSI ' },
        { id: 473, countryId: 13, name: ' MORALES ' },
        { id: 549, countryId: 13, name: ' PINILLOS ' },
        { id: 580, countryId: 13, name: ' REGIDOR ' },
        { id: 600, countryId: 13, name: ' RIO VIEJO ' },
        { id: 620, countryId: 13, name: ' SAN CRISTOBAL ' },
        { id: 647, countryId: 13, name: ' SAN ESTANISLAO ' },
        { id: 650, countryId: 13, name: ' SAN FERNANDO ' },
        { id: 654, countryId: 13, name: ' SAN JACINTO ' },
        { id: 655, countryId: 13, name: ' SAN JACINTO DEL CAUCA ' },
        { id: 657, countryId: 13, name: ' SAN JUAN NEPOMUCENO ' },
        { id: 667, countryId: 13, name: ' SAN MARTIN DE LOBA ' },
        { id: 670, countryId: 13, name: ' SAN PABLO ' },
        { id: 673, countryId: 13, name: ' SANTA CATALINA ' },
        { id: 683, countryId: 13, name: ' SANTA ROSA ' },
        { id: 688, countryId: 13, name: ' SANTA ROSA DEL SUR ' },
        { id: 744, countryId: 13, name: ' SIMITI ' },
        { id: 760, countryId: 13, name: ' SOPLAVIENTO ' },
        { id: 780, countryId: 13, name: ' TALAIGUA NUEVO ' },
        { id: 810, countryId: 13, name: ' TIQUISIO ' },
        { id: 836, countryId: 13, name: ' TURBACO ' },
        { id: 838, countryId: 13, name: ' TURBANA ' },
        { id: 873, countryId: 13, name: ' VILLANUEVA ' },
        { id: 894, countryId: 13, name: ' ZAMBRANO ' },
        { id: 1, countryId: 15, name: ' TUNJA ' },
        { id: 22, countryId: 15, name: ' ALMEIDA ' },
        { id: 47, countryId: 15, name: ' AQUITANIA ' },
        { id: 51, countryId: 15, name: ' ARCABUCO ' },
        { id: 87, countryId: 15, name: ' BELEN ' },
        { id: 90, countryId: 15, name: ' BERBEO ' },
        { id: 92, countryId: 15, name: ' BETEITIVA ' },
        { id: 97, countryId: 15, name: ' BOAVITA ' },
        { id: 104, countryId: 15, name: ' BOYACA ' },
        { id: 106, countryId: 15, name: ' BRICEÑO ' },
        { id: 109, countryId: 15, name: ' BUENAVISTA ' },
        { id: 114, countryId: 15, name: ' BUSBANZA ' },
        { id: 131, countryId: 15, name: ' CALDAS ' },
        { id: 135, countryId: 15, name: ' CAMPOHERMOSO ' },
        { id: 162, countryId: 15, name: ' CERINZA ' },
        { id: 172, countryId: 15, name: ' CHINAVITA ' },
        { id: 176, countryId: 15, name: ' CHIQUINQUIRA ' },
        { id: 180, countryId: 15, name: ' CHISCAS ' },
        { id: 183, countryId: 15, name: ' CHITA ' },
        { id: 185, countryId: 15, name: ' CHITARAQUE ' },
        { id: 187, countryId: 15, name: ' CHIVATA ' },
        { id: 189, countryId: 15, name: ' CIENEGA ' },
        { id: 204, countryId: 15, name: ' COMBITA ' },
        { id: 212, countryId: 15, name: ' COPER ' },
        { id: 215, countryId: 15, name: ' CORRALES ' },
        { id: 218, countryId: 15, name: ' COVARACHIA ' },
        { id: 223, countryId: 15, name: ' CUBARA ' },
        { id: 224, countryId: 15, name: ' CUCAITA ' },
        { id: 226, countryId: 15, name: ' CUITIVA ' },
        { id: 232, countryId: 15, name: ' CHIQUIZA ' },
        { id: 236, countryId: 15, name: ' CHIVOR ' },
        { id: 238, countryId: 15, name: ' DUITAMA ' },
        { id: 244, countryId: 15, name: ' EL COCUY ' },
        { id: 248, countryId: 15, name: ' EL ESPINO ' },
        { id: 272, countryId: 15, name: ' FIRAVITOBA ' },
        { id: 276, countryId: 15, name: ' FLORESTA ' },
        { id: 293, countryId: 15, name: ' GACHANTIVA ' },
        { id: 296, countryId: 15, name: ' GAMEZA ' },
        { id: 299, countryId: 15, name: ' GARAGOA ' },
        { id: 317, countryId: 15, name: ' GUACAMAYAS ' },
        { id: 322, countryId: 15, name: ' GUATEQUE ' },
        { id: 325, countryId: 15, name: ' GUAYATA ' },
        { id: 332, countryId: 15, name: ' GsICAN ' },
        { id: 362, countryId: 15, name: ' IZA ' },
        { id: 367, countryId: 15, name: ' JENESANO ' },
        { id: 368, countryId: 15, name: ' JERICO ' },
        { id: 377, countryId: 15, name: ' LABRANZAGRANDE ' },
        { id: 380, countryId: 15, name: ' LA CAPILLA ' },
        { id: 401, countryId: 15, name: ' LA VICTORIA ' },
        { id: 403, countryId: 15, name: ' LA UVITA ' },
        { id: 407, countryId: 15, name: ' VILLA DE LEYVA ' },
        { id: 425, countryId: 15, name: ' MACANAL ' },
        { id: 442, countryId: 15, name: ' MARIPI ' },
        { id: 455, countryId: 15, name: ' MIRAFLORES ' },
        { id: 464, countryId: 15, name: ' MONGUA ' },
        { id: 466, countryId: 15, name: ' MONGUI ' },
        { id: 469, countryId: 15, name: ' MONIQUIRA ' },
        { id: 476, countryId: 15, name: ' MOTAVITA ' },
        { id: 480, countryId: 15, name: ' MUZO ' },
        { id: 491, countryId: 15, name: ' NOBSA ' },
        { id: 494, countryId: 15, name: ' NUEVO COLON ' },
        { id: 500, countryId: 15, name: ' OICATA ' },
        { id: 507, countryId: 15, name: ' OTANCHE ' },
        { id: 511, countryId: 15, name: ' PACHAVITA ' },
        { id: 514, countryId: 15, name: ' PAEZ ' },
        { id: 516, countryId: 15, name: ' PAIPA ' },
        { id: 518, countryId: 15, name: ' PAJARITO ' },
        { id: 522, countryId: 15, name: ' PANQUEBA ' },
        { id: 531, countryId: 15, name: ' PAUNA ' },
        { id: 533, countryId: 15, name: ' PAYA ' },
        { id: 537, countryId: 15, name: ' PAZ DE RIO ' },
        { id: 542, countryId: 15, name: ' PESCA ' },
        { id: 550, countryId: 15, name: ' PISBA ' },
        { id: 572, countryId: 15, name: ' PUERTO BOYACA ' },
        { id: 580, countryId: 15, name: ' QUIPAMA ' },
        { id: 599, countryId: 15, name: ' RAMIRIQUI ' },
        { id: 600, countryId: 15, name: ' RAQUIRA ' },
        { id: 621, countryId: 15, name: ' RONDON ' },
        { id: 632, countryId: 15, name: ' SABOYA ' },
        { id: 638, countryId: 15, name: ' SACHICA ' },
        { id: 646, countryId: 15, name: ' SAMACA ' },
        { id: 660, countryId: 15, name: ' SAN EDUARDO ' },
        { id: 664, countryId: 15, name: ' SAN JOSE DE PARE ' },
        { id: 667, countryId: 15, name: ' SAN LUIS DE GACENO ' },
        { id: 673, countryId: 15, name: ' SAN MATEO ' },
        { id: 676, countryId: 15, name: ' SAN MIGUEL DE SEMA ' },
        { id: 681, countryId: 15, name: ' SAN PABLO DE BORBUR ' },
        { id: 686, countryId: 15, name: ' SANTANA ' },
        { id: 690, countryId: 15, name: ' SANTA MARIA ' },
        { id: 693, countryId: 15, name: ' SANTA ROSA DE VITERBO ' },
        { id: 696, countryId: 15, name: ' SANTA SOFIA ' },
        { id: 720, countryId: 15, name: ' SATIVANORTE ' },
        { id: 723, countryId: 15, name: ' SATIVASUR ' },
        { id: 740, countryId: 15, name: ' SIACHOQUE ' },
        { id: 753, countryId: 15, name: ' SOATA ' },
        { id: 755, countryId: 15, name: ' SOCOTA ' },
        { id: 757, countryId: 15, name: ' SOCHA ' },
        { id: 759, countryId: 15, name: ' SOGAMOSO ' },
        { id: 761, countryId: 15, name: ' SOMONDOCO ' },
        { id: 762, countryId: 15, name: ' SORA ' },
        { id: 763, countryId: 15, name: ' SOTAQUIRA ' },
        { id: 764, countryId: 15, name: ' SORACA ' },
        { id: 774, countryId: 15, name: ' SUSACON ' },
        { id: 776, countryId: 15, name: ' SUTAMARCHAN ' },
        { id: 778, countryId: 15, name: ' SUTATENZA ' },
        { id: 790, countryId: 15, name: ' TASCO ' },
        { id: 798, countryId: 15, name: ' TENZA ' },
        { id: 804, countryId: 15, name: ' TIBANA ' },
        { id: 806, countryId: 15, name: ' TIBASOSA ' },
        { id: 808, countryId: 15, name: ' TINJACA ' },
        { id: 810, countryId: 15, name: ' TIPACOQUE ' },
        { id: 814, countryId: 15, name: ' TOCA ' },
        { id: 816, countryId: 15, name: ' TOGsI ' },
        { id: 820, countryId: 15, name: ' TOPAGA ' },
        { id: 822, countryId: 15, name: ' TOTA ' },
        { id: 832, countryId: 15, name: ' TUNUNGUA ' },
        { id: 835, countryId: 15, name: ' TURMEQUE ' },
        { id: 837, countryId: 15, name: ' TUTA ' },
        { id: 839, countryId: 15, name: ' TUTAZA ' },
        { id: 842, countryId: 15, name: ' UMBITA ' },
        { id: 861, countryId: 15, name: ' VENTAQUEMADA ' },
        { id: 879, countryId: 15, name: ' VIRACACHA ' },
        { id: 897, countryId: 15, name: ' ZETAQUIRA ' },
        { id: 1, countryId: 17, name: ' MANIZALES ' },
        { id: 13, countryId: 17, name: ' AGUADAS ' },
        { id: 42, countryId: 17, name: ' ANSERMA ' },
        { id: 50, countryId: 17, name: ' ARANZAZU ' },
        { id: 88, countryId: 17, name: ' BELALCAZAR ' },
        { id: 174, countryId: 17, name: ' CHINCHINA ' },
        { id: 272, countryId: 17, name: ' FILADELFIA ' },
        { id: 380, countryId: 17, name: ' LA DORADA ' },
        { id: 388, countryId: 17, name: ' LA MERCED ' },
        { id: 433, countryId: 17, name: ' MANZANARES ' },
        { id: 442, countryId: 17, name: ' MARMATO ' },
        { id: 444, countryId: 17, name: ' MARQUETALIA ' },
        { id: 446, countryId: 17, name: ' MARULANDA ' },
        { id: 486, countryId: 17, name: ' NEIRA ' },
        { id: 495, countryId: 17, name: ' NORCASIA ' },
        { id: 513, countryId: 17, name: ' PACORA ' },
        { id: 524, countryId: 17, name: ' PALESTINA ' },
        { id: 541, countryId: 17, name: ' PENSILVANIA ' },
        { id: 614, countryId: 17, name: ' RIOSUCIO ' },
        { id: 616, countryId: 17, name: ' RISARALDA ' },
        { id: 653, countryId: 17, name: ' SALAMINA ' },
        { id: 662, countryId: 17, name: ' SAMANA ' },
        { id: 665, countryId: 17, name: ' SAN JOSE ' },
        { id: 777, countryId: 17, name: ' SUPIA ' },
        { id: 867, countryId: 17, name: ' VICTORIA ' },
        { id: 873, countryId: 17, name: ' VILLAMARIA ' },
        { id: 877, countryId: 17, name: ' VITERBO ' },
        { id: 1, countryId: 18, name: ' FLORENCIA ' },
        { id: 29, countryId: 18, name: ' ALBANIA ' },
        { id: 94, countryId: 18, name: ' BELEN DE LOS ANDAQUIES ' },
        { id: 150, countryId: 18, name: ' CARTAGENA DEL CHAIRA ' },
        { id: 205, countryId: 18, name: ' CURILLO ' },
        { id: 247, countryId: 18, name: ' EL DONCELLO ' },
        { id: 256, countryId: 18, name: ' EL PAUJIL ' },
        { id: 410, countryId: 18, name: ' LA MONTAÑITA ' },
        { id: 460, countryId: 18, name: ' MILAN ' },
        { id: 479, countryId: 18, name: ' MORELIA ' },
        { id: 592, countryId: 18, name: ' PUERTO RICO ' },
        { id: 610, countryId: 18, name: ' SAN JOSE DEL FRAGUA ' },
        { id: 753, countryId: 18, name: ' SAN VICENTE DEL CAGUAN ' },
        { id: 756, countryId: 18, name: ' SOLANO ' },
        { id: 785, countryId: 18, name: ' SOLITA ' },
        { id: 860, countryId: 18, name: ' VALPARAISO ' },
        { id: 1, countryId: 19, name: ' POPAYAN ' },
        { id: 22, countryId: 19, name: ' ALMAGUER ' },
        { id: 50, countryId: 19, name: ' ARGELIA ' },
        { id: 75, countryId: 19, name: ' BALBOA ' },
        { id: 100, countryId: 19, name: ' BOLIVAR ' },
        { id: 110, countryId: 19, name: ' BUENOS AIRES ' },
        { id: 130, countryId: 19, name: ' CAJIBIO ' },
        { id: 137, countryId: 19, name: ' CALDONO ' },
        { id: 142, countryId: 19, name: ' CALOTO ' },
        { id: 212, countryId: 19, name: ' CORINTO ' },
        { id: 256, countryId: 19, name: ' EL TAMBO ' },
        { id: 290, countryId: 19, name: ' FLORENCIA ' },
        { id: 300, countryId: 19, name: ' GUACHENE ' },
        { id: 318, countryId: 19, name: ' GUAPI ' },
        { id: 355, countryId: 19, name: ' INZA ' },
        { id: 364, countryId: 19, name: ' JAMBALO ' },
        { id: 392, countryId: 19, name: ' LA SIERRA ' },
        { id: 397, countryId: 19, name: ' LA VEGA ' },
        { id: 418, countryId: 19, name: ' LOPEZ ' },
        { id: 450, countryId: 19, name: ' MERCADERES ' },
        { id: 455, countryId: 19, name: ' MIRANDA ' },
        { id: 473, countryId: 19, name: ' MORALES ' },
        { id: 513, countryId: 19, name: ' PADILLA ' },
        { id: 517, countryId: 19, name: ' PAEZ ' },
        { id: 532, countryId: 19, name: ' PATIA ' },
        { id: 533, countryId: 19, name: ' PIAMONTE ' },
        { id: 548, countryId: 19, name: ' PIENDAMO ' },
        { id: 573, countryId: 19, name: ' PUERTO TEJADA ' },
        { id: 585, countryId: 19, name: ' PURACE ' },
        { id: 622, countryId: 19, name: ' ROSAS ' },
        { id: 693, countryId: 19, name: ' SAN SEBASTIAN ' },
        { id: 698, countryId: 19, name: ' SANTANDER DE QUILICHAO ' },
        { id: 701, countryId: 19, name: ' SANTA ROSA ' },
        { id: 743, countryId: 19, name: ' SILVIA ' },
        { id: 760, countryId: 19, name: ' SOTARA ' },
        { id: 780, countryId: 19, name: ' SUAREZ ' },
        { id: 785, countryId: 19, name: ' SUCRE ' },
        { id: 807, countryId: 19, name: ' TIMBIO ' },
        { id: 809, countryId: 19, name: ' TIMBIQUI ' },
        { id: 821, countryId: 19, name: ' TORIBIO ' },
        { id: 824, countryId: 19, name: ' TOTORO ' },
        { id: 845, countryId: 19, name: ' VILLA RICA ' },
        { id: 1, countryId: 20, name: ' VALLEDUPAR ' },
        { id: 11, countryId: 20, name: ' AGUACHICA ' },
        { id: 13, countryId: 20, name: ' AGUSTIN CODAZZI ' },
        { id: 32, countryId: 20, name: ' ASTREA ' },
        { id: 45, countryId: 20, name: ' BECERRIL ' },
        { id: 60, countryId: 20, name: ' BOSCONIA ' },
        { id: 175, countryId: 20, name: ' CHIMICHAGUA ' },
        { id: 178, countryId: 20, name: ' CHIRIGUANA ' },
        { id: 228, countryId: 20, name: ' CURUMANI ' },
        { id: 238, countryId: 20, name: ' EL COPEY ' },
        { id: 250, countryId: 20, name: ' EL PASO ' },
        { id: 295, countryId: 20, name: ' GAMARRA ' },
        { id: 310, countryId: 20, name: ' GONZALEZ ' },
        { id: 383, countryId: 20, name: ' LA GLORIA ' },
        { id: 400, countryId: 20, name: ' LA JAGUA DE IBIRICO ' },
        { id: 443, countryId: 20, name: ' MANAURE ' },
        { id: 517, countryId: 20, name: ' PAILITAS ' },
        { id: 550, countryId: 20, name: ' PELAYA ' },
        { id: 570, countryId: 20, name: ' PUEBLO BELLO ' },
        { id: 614, countryId: 20, name: ' RIO DE ORO ' },
        { id: 621, countryId: 20, name: ' LA PAZ ' },
        { id: 710, countryId: 20, name: ' SAN ALBERTO ' },
        { id: 750, countryId: 20, name: ' SAN DIEGO ' },
        { id: 770, countryId: 20, name: ' SAN MARTIN ' },
        { id: 787, countryId: 20, name: ' TAMALAMEQUE ' },
        { id: 1, countryId: 23, name: ' MONTERIA ' },
        { id: 68, countryId: 23, name: ' AYAPEL ' },
        { id: 79, countryId: 23, name: ' BUENAVISTA ' },
        { id: 90, countryId: 23, name: ' CANALETE ' },
        { id: 162, countryId: 23, name: ' CERETE ' },
        { id: 168, countryId: 23, name: ' CHIMA ' },
        { id: 182, countryId: 23, name: ' CHINU ' },
        { id: 189, countryId: 23, name: ' CIENAGA DE ORO ' },
        { id: 300, countryId: 23, name: ' COTORRA ' },
        { id: 350, countryId: 23, name: ' LA APARTADA ' },
        { id: 417, countryId: 23, name: ' LORICA ' },
        { id: 419, countryId: 23, name: ' LOS CORDOBAS ' },
        { id: 464, countryId: 23, name: ' MOMIL ' },
        { id: 466, countryId: 23, name: ' MONTELIBANO ' },
        { id: 500, countryId: 23, name: ' MOÑITOS ' },
        { id: 555, countryId: 23, name: ' PLANETA RICA ' },
        { id: 570, countryId: 23, name: ' PUEBLO NUEVO ' },
        { id: 574, countryId: 23, name: ' PUERTO ESCONDIDO ' },
        { id: 580, countryId: 23, name: ' PUERTO LIBERTADOR ' },
        { id: 586, countryId: 23, name: ' PURISIMA ' },
        { id: 660, countryId: 23, name: ' SAHAGUN ' },
        { id: 670, countryId: 23, name: ' SAN ANDRES SOTAVENTO ' },
        { id: 672, countryId: 23, name: ' SAN ANTERO ' },
        { id: 675, countryId: 23, name: ' SAN BERNARDO DEL VIENTO ' },
        { id: 678, countryId: 23, name: ' SAN CARLOS ' },
        { id: 686, countryId: 23, name: ' SAN PELAYO ' },
        { id: 807, countryId: 23, name: ' TIERRALTA ' },
        { id: 855, countryId: 23, name: ' VALENCIA ' },
        { id: 1, countryId: 25, name: ' AGUA DE DIOS ' },
        { id: 19, countryId: 25, name: ' ALBAN ' },
        { id: 35, countryId: 25, name: ' ANAPOIMA ' },
        { id: 40, countryId: 25, name: ' ANOLAIMA ' },
        { id: 53, countryId: 25, name: ' ARBELAEZ ' },
        { id: 86, countryId: 25, name: ' BELTRAN ' },
        { id: 95, countryId: 25, name: ' BITUIMA ' },
        { id: 99, countryId: 25, name: ' BOJACA ' },
        { id: 120, countryId: 25, name: ' CABRERA ' },
        { id: 123, countryId: 25, name: ' CACHIPAY ' },
        { id: 126, countryId: 25, name: ' CAJICA ' },
        { id: 148, countryId: 25, name: ' CAPARRAPI ' },
        { id: 151, countryId: 25, name: ' CAQUEZA ' },
        { id: 154, countryId: 25, name: ' CARMEN DE CARUPA ' },
        { id: 168, countryId: 25, name: ' CHAGUANI ' },
        { id: 175, countryId: 25, name: ' CHIA ' },
        { id: 178, countryId: 25, name: ' CHIPAQUE ' },
        { id: 181, countryId: 25, name: ' CHOACHI ' },
        { id: 183, countryId: 25, name: ' CHOCONTA ' },
        { id: 200, countryId: 25, name: ' COGUA ' },
        { id: 214, countryId: 25, name: ' COTA ' },
        { id: 224, countryId: 25, name: ' CUCUNUBA ' },
        { id: 245, countryId: 25, name: ' EL COLEGIO ' },
        { id: 258, countryId: 25, name: ' EL PEÑON ' },
        { id: 260, countryId: 25, name: ' EL ROSAL ' },
        { id: 269, countryId: 25, name: ' FACATATIVA ' },
        { id: 279, countryId: 25, name: ' FOMEQUE ' },
        { id: 281, countryId: 25, name: ' FOSCA ' },
        { id: 286, countryId: 25, name: ' FUNZA ' },
        { id: 288, countryId: 25, name: ' FUQUENE ' },
        { id: 290, countryId: 25, name: ' FUSAGASUGA ' },
        { id: 293, countryId: 25, name: ' GACHALA ' },
        { id: 295, countryId: 25, name: ' GACHANCIPA ' },
        { id: 297, countryId: 25, name: ' GACHETA ' },
        { id: 299, countryId: 25, name: ' GAMA ' },
        { id: 307, countryId: 25, name: ' GIRARDOT ' },
        { id: 312, countryId: 25, name: ' GRANADA ' },
        { id: 317, countryId: 25, name: ' GUACHETA ' },
        { id: 320, countryId: 25, name: ' GUADUAS ' },
        { id: 322, countryId: 25, name: ' GUASCA ' },
        { id: 324, countryId: 25, name: ' GUATAQUI ' },
        { id: 326, countryId: 25, name: ' GUATAVITA ' },
        { id: 328, countryId: 25, name: ' GUAYABAL DE SIQUIMA ' },
        { id: 335, countryId: 25, name: ' GUAYABETAL ' },
        { id: 339, countryId: 25, name: ' GUTIERREZ ' },
        { id: 368, countryId: 25, name: ' JERUSALEN ' },
        { id: 372, countryId: 25, name: ' JUNIN ' },
        { id: 377, countryId: 25, name: ' LA CALERA ' },
        { id: 386, countryId: 25, name: ' LA MESA ' },
        { id: 394, countryId: 25, name: ' LA PALMA ' },
        { id: 398, countryId: 25, name: ' LA PEÑA ' },
        { id: 402, countryId: 25, name: ' LA VEGA ' },
        { id: 407, countryId: 25, name: ' LENGUAZAQUE ' },
        { id: 426, countryId: 25, name: ' MACHETA ' },
        { id: 430, countryId: 25, name: ' MADRID ' },
        { id: 436, countryId: 25, name: ' MANTA ' },
        { id: 438, countryId: 25, name: ' MEDINA ' },
        { id: 473, countryId: 25, name: ' MOSQUERA ' },
        { id: 483, countryId: 25, name: ' NARIÑO ' },
        { id: 486, countryId: 25, name: ' NEMOCON ' },
        { id: 488, countryId: 25, name: ' NILO ' },
        { id: 489, countryId: 25, name: ' NIMAIMA ' },
        { id: 491, countryId: 25, name: ' NOCAIMA ' },
        { id: 506, countryId: 25, name: ' VENECIA ' },
        { id: 513, countryId: 25, name: ' PACHO ' },
        { id: 518, countryId: 25, name: ' PAIME ' },
        { id: 524, countryId: 25, name: ' PANDI ' },
        { id: 530, countryId: 25, name: ' PARATEBUENO ' },
        { id: 535, countryId: 25, name: ' PASCA ' },
        { id: 572, countryId: 25, name: ' PUERTO SALGAR ' },
        { id: 580, countryId: 25, name: ' PULI ' },
        { id: 592, countryId: 25, name: ' QUEBRADANEGRA ' },
        { id: 594, countryId: 25, name: ' QUETAME ' },
        { id: 596, countryId: 25, name: ' QUIPILE ' },
        { id: 599, countryId: 25, name: ' APULO ' },
        { id: 612, countryId: 25, name: ' RICAURTE ' },
        { id: 645, countryId: 25, name: ' SAN ANTONIO DEL TEQUENDAMA ' },
        { id: 649, countryId: 25, name: ' SAN BERNARDO ' },
        { id: 653, countryId: 25, name: ' SAN CAYETANO ' },
        { id: 658, countryId: 25, name: ' SAN FRANCISCO ' },
        { id: 662, countryId: 25, name: ' SAN JUAN DE RIO SECO ' },
        { id: 718, countryId: 25, name: ' SASAIMA ' },
        { id: 736, countryId: 25, name: ' SESQUILE ' },
        { id: 740, countryId: 25, name: ' SIBATE ' },
        { id: 743, countryId: 25, name: ' SILVANIA ' },
        { id: 745, countryId: 25, name: ' SIMIJACA ' },
        { id: 754, countryId: 25, name: ' SOACHA ' },
        { id: 758, countryId: 25, name: ' SOPO ' },
        { id: 769, countryId: 25, name: ' SUBACHOQUE ' },
        { id: 772, countryId: 25, name: ' SUESCA ' },
        { id: 777, countryId: 25, name: ' SUPATA ' },
        { id: 779, countryId: 25, name: ' SUSA ' },
        { id: 781, countryId: 25, name: ' SUTATAUSA ' },
        { id: 785, countryId: 25, name: ' TABIO ' },
        { id: 793, countryId: 25, name: ' TAUSA ' },
        { id: 797, countryId: 25, name: ' TENA ' },
        { id: 799, countryId: 25, name: ' TENJO ' },
        { id: 805, countryId: 25, name: ' TIBACUY ' },
        { id: 807, countryId: 25, name: ' TIBIRITA ' },
        { id: 815, countryId: 25, name: ' TOCAIMA ' },
        { id: 817, countryId: 25, name: ' TOCANCIPA ' },
        { id: 823, countryId: 25, name: ' TOPAIPI ' },
        { id: 839, countryId: 25, name: ' UBALA ' },
        { id: 841, countryId: 25, name: ' UBAQUE ' },
        { id: 843, countryId: 25, name: ' VILLA DE SAN DIEGO DE UBATE ' },
        { id: 845, countryId: 25, name: ' UNE ' },
        { id: 851, countryId: 25, name: ' UTICA ' },
        { id: 862, countryId: 25, name: ' VERGARA ' },
        { id: 867, countryId: 25, name: ' VIANI ' },
        { id: 871, countryId: 25, name: ' VILLAGOMEZ ' },
        { id: 873, countryId: 25, name: ' VILLAPINZON ' },
        { id: 875, countryId: 25, name: ' VILLETA ' },
        { id: 878, countryId: 25, name: ' VIOTA ' },
        { id: 885, countryId: 25, name: ' YACOPI ' },
        { id: 898, countryId: 25, name: ' ZIPACON ' },
        { id: 899, countryId: 25, name: ' ZIPAQUIRA ' },
        { id: 1, countryId: 27, name: ' QUIBDO ' },
        { id: 6, countryId: 27, name: ' ACANDI ' },
        { id: 25, countryId: 27, name: ' ALTO BAUDO ' },
        { id: 50, countryId: 27, name: ' ATRATO ' },
        { id: 73, countryId: 27, name: ' BAGADO ' },
        { id: 75, countryId: 27, name: ' BAHIA SOLANO ' },
        { id: 77, countryId: 27, name: ' BAJO BAUDO ' },
        { id: 99, countryId: 27, name: ' BOJAYA ' },
        { id: 135, countryId: 27, name: ' EL CANTON DEL SAN PABLO ' },
        { id: 150, countryId: 27, name: ' CARMEN DEL DARIEN ' },
        { id: 160, countryId: 27, name: ' CERTEGUI ' },
        { id: 205, countryId: 27, name: ' CONDOTO ' },
        { id: 245, countryId: 27, name: ' EL CARMEN DE ATRATO ' },
        { id: 250, countryId: 27, name: ' EL LITORAL DEL SAN JUAN ' },
        { id: 361, countryId: 27, name: ' ISTMINA ' },
        { id: 372, countryId: 27, name: ' JURADO ' },
        { id: 413, countryId: 27, name: ' LLORO ' },
        { id: 425, countryId: 27, name: ' MEDIO ATRATO ' },
        { id: 430, countryId: 27, name: ' MEDIO BAUDO ' },
        { id: 450, countryId: 27, name: ' MEDIO SAN JUAN ' },
        { id: 491, countryId: 27, name: ' NOVITA ' },
        { id: 495, countryId: 27, name: ' NUQUI ' },
        { id: 580, countryId: 27, name: ' RIO IRO ' },
        { id: 600, countryId: 27, name: ' RIO QUITO ' },
        { id: 615, countryId: 27, name: ' RIOSUCIO ' },
        { id: 660, countryId: 27, name: ' SAN JOSE DEL PALMAR ' },
        { id: 745, countryId: 27, name: ' SIPI ' },
        { id: 787, countryId: 27, name: ' TADO ' },
        { id: 800, countryId: 27, name: ' UNGUIA ' },
        { id: 810, countryId: 27, name: ' UNION PANAMERICANA ' },
        { id: 1, countryId: 41, name: ' NEIVA ' },
        { id: 6, countryId: 41, name: ' ACEVEDO ' },
        { id: 13, countryId: 41, name: ' AGRADO ' },
        { id: 16, countryId: 41, name: ' AIPE ' },
        { id: 20, countryId: 41, name: ' ALGECIRAS ' },
        { id: 26, countryId: 41, name: ' ALTAMIRA ' },
        { id: 78, countryId: 41, name: ' BARAYA ' },
        { id: 132, countryId: 41, name: ' CAMPOALEGRE ' },
        { id: 206, countryId: 41, name: ' COLOMBIA ' },
        { id: 244, countryId: 41, name: ' ELIAS ' },
        { id: 298, countryId: 41, name: ' GARZON ' },
        { id: 306, countryId: 41, name: ' GIGANTE ' },
        { id: 319, countryId: 41, name: ' GUADALUPE ' },
        { id: 349, countryId: 41, name: ' HOBO ' },
        { id: 357, countryId: 41, name: ' IQUIRA ' },
        { id: 359, countryId: 41, name: ' ISNOS ' },
        { id: 378, countryId: 41, name: ' LA ARGENTINA ' },
        { id: 396, countryId: 41, name: ' LA PLATA ' },
        { id: 483, countryId: 41, name: ' NATAGA ' },
        { id: 503, countryId: 41, name: ' OPORAPA ' },
        { id: 518, countryId: 41, name: ' PAICOL ' },
        { id: 524, countryId: 41, name: ' PALERMO ' },
        { id: 530, countryId: 41, name: ' PALESTINA ' },
        { id: 548, countryId: 41, name: ' PITAL ' },
        { id: 551, countryId: 41, name: ' PITALITO ' },
        { id: 615, countryId: 41, name: ' RIVERA ' },
        { id: 660, countryId: 41, name: ' SALADOBLANCO ' },
        { id: 668, countryId: 41, name: ' SAN AGUSTIN ' },
        { id: 676, countryId: 41, name: ' SANTA MARIA ' },
        { id: 770, countryId: 41, name: ' SUAZA ' },
        { id: 791, countryId: 41, name: ' TARQUI ' },
        { id: 797, countryId: 41, name: ' TESALIA ' },
        { id: 799, countryId: 41, name: ' TELLO ' },
        { id: 801, countryId: 41, name: ' TERUEL ' },
        { id: 807, countryId: 41, name: ' TIMANA ' },
        { id: 872, countryId: 41, name: ' VILLAVIEJA ' },
        { id: 885, countryId: 41, name: ' YAGUARA ' },
        { id: 1, countryId: 44, name: ' RIOHACHA ' },
        { id: 35, countryId: 44, name: ' ALBANIA ' },
        { id: 78, countryId: 44, name: ' BARRANCAS ' },
        { id: 90, countryId: 44, name: ' DIBULLA ' },
        { id: 98, countryId: 44, name: ' DISTRACCION ' },
        { id: 110, countryId: 44, name: ' EL MOLINO ' },
        { id: 279, countryId: 44, name: ' FONSECA ' },
        { id: 378, countryId: 44, name: ' HATONUEVO ' },
        { id: 420, countryId: 44, name: ' LA JAGUA DEL PILAR ' },
        { id: 430, countryId: 44, name: ' MAICAO ' },
        { id: 560, countryId: 44, name: ' MANAURE ' },
        { id: 650, countryId: 44, name: ' SAN JUAN DEL CESAR ' },
        { id: 847, countryId: 44, name: ' URIBIA ' },
        { id: 855, countryId: 44, name: ' URUMITA ' },
        { id: 874, countryId: 44, name: ' VILLANUEVA ' },
        { id: 1, countryId: 47, name: ' SANTA MARTA ' },
        { id: 30, countryId: 47, name: ' ALGARROBO ' },
        { id: 53, countryId: 47, name: ' ARACATACA ' },
        { id: 58, countryId: 47, name: ' ARIGUANI ' },
        { id: 161, countryId: 47, name: ' CERRO SAN ANTONIO ' },
        { id: 170, countryId: 47, name: ' CHIBOLO ' },
        { id: 189, countryId: 47, name: ' CIENAGA ' },
        { id: 205, countryId: 47, name: ' CONCORDIA ' },
        { id: 245, countryId: 47, name: ' EL BANCO ' },
        { id: 258, countryId: 47, name: ' EL PIÑON ' },
        { id: 268, countryId: 47, name: ' EL RETEN ' },
        { id: 288, countryId: 47, name: ' FUNDACION ' },
        { id: 318, countryId: 47, name: ' GUAMAL ' },
        { id: 460, countryId: 47, name: ' NUEVA GRANADA ' },
        { id: 541, countryId: 47, name: ' PEDRAZA ' },
        { id: 545, countryId: 47, name: ' PIJIÑO DEL CARMEN ' },
        { id: 551, countryId: 47, name: ' PIVIJAY ' },
        { id: 555, countryId: 47, name: ' PLATO ' },
        { id: 570, countryId: 47, name: ' PUEBLOVIEJO ' },
        { id: 605, countryId: 47, name: ' REMOLINO ' },
        { id: 660, countryId: 47, name: ' SABANAS DE SAN ANGEL ' },
        { id: 675, countryId: 47, name: ' SALAMINA ' },
        { id: 692, countryId: 47, name: ' SAN SEBASTIAN DE BUENAVISTA ' },
        { id: 703, countryId: 47, name: ' SAN ZENON ' },
        { id: 707, countryId: 47, name: ' SANTA ANA ' },
        { id: 720, countryId: 47, name: ' SANTA BARBARA DE PINTO ' },
        { id: 745, countryId: 47, name: ' SITIONUEVO ' },
        { id: 798, countryId: 47, name: ' TENERIFE ' },
        { id: 960, countryId: 47, name: ' ZAPAYAN ' },
        { id: 980, countryId: 47, name: ' ZONA BANANERA ' },
        { id: 1, countryId: 50, name: ' VILLAVICENCIO ' },
        { id: 6, countryId: 50, name: ' ACACIAS ' },
        { id: 110, countryId: 50, name: ' BARRANCA DE UPIA ' },
        { id: 124, countryId: 50, name: ' CABUYARO ' },
        { id: 150, countryId: 50, name: ' CASTILLA LA NUEVA ' },
        { id: 223, countryId: 50, name: ' CUBARRAL ' },
        { id: 226, countryId: 50, name: ' CUMARAL ' },
        { id: 245, countryId: 50, name: ' EL CALVARIO ' },
        { id: 251, countryId: 50, name: ' EL CASTILLO ' },
        { id: 270, countryId: 50, name: ' EL DORADO ' },
        { id: 287, countryId: 50, name: ' FUENTE DE ORO ' },
        { id: 313, countryId: 50, name: ' GRANADA ' },
        { id: 318, countryId: 50, name: ' GUAMAL ' },
        { id: 325, countryId: 50, name: ' MAPIRIPAN ' },
        { id: 330, countryId: 50, name: ' MESETAS ' },
        { id: 350, countryId: 50, name: ' LA MACARENA ' },
        { id: 370, countryId: 50, name: ' URIBE ' },
        { id: 400, countryId: 50, name: ' LEJANIAS ' },
        { id: 450, countryId: 50, name: ' PUERTO CONCORDIA ' },
        { id: 568, countryId: 50, name: ' PUERTO GAITAN ' },
        { id: 573, countryId: 50, name: ' PUERTO LOPEZ ' },
        { id: 577, countryId: 50, name: ' PUERTO LLERAS ' },
        { id: 590, countryId: 50, name: ' PUERTO RICO ' },
        { id: 606, countryId: 50, name: ' RESTREPO ' },
        { id: 680, countryId: 50, name: ' SAN CARLOS DE GUAROA ' },
        { id: 683, countryId: 50, name: ' SAN JUAN DE ARAMA ' },
        { id: 686, countryId: 50, name: ' SAN JUANITO ' },
        { id: 689, countryId: 50, name: ' SAN MARTIN ' },
        { id: 711, countryId: 50, name: ' VISTAHERMOSA ' },
        { id: 1, countryId: 52, name: ' PASTO ' },
        { id: 19, countryId: 52, name: ' ALBAN ' },
        { id: 22, countryId: 52, name: ' ALDANA ' },
        { id: 36, countryId: 52, name: ' ANCUYA ' },
        { id: 51, countryId: 52, name: ' ARBOLEDA ' },
        { id: 79, countryId: 52, name: ' BARBACOAS ' },
        { id: 83, countryId: 52, name: ' BELEN ' },
        { id: 110, countryId: 52, name: ' BUESACO ' },
        { id: 203, countryId: 52, name: ' COLON ' },
        { id: 207, countryId: 52, name: ' CONSACA ' },
        { id: 210, countryId: 52, name: ' CONTADERO ' },
        { id: 215, countryId: 52, name: ' CORDOBA ' },
        { id: 224, countryId: 52, name: ' CUASPUD ' },
        { id: 227, countryId: 52, name: ' CUMBAL ' },
        { id: 233, countryId: 52, name: ' CUMBITARA ' },
        { id: 240, countryId: 52, name: ' CHACHAGsI ' },
        { id: 250, countryId: 52, name: ' EL CHARCO ' },
        { id: 254, countryId: 52, name: ' EL PEÑOL ' },
        { id: 256, countryId: 52, name: ' EL ROSARIO ' },
        { id: 258, countryId: 52, name: ' EL TABLON DE GOMEZ ' },
        { id: 260, countryId: 52, name: ' EL TAMBO ' },
        { id: 287, countryId: 52, name: ' FUNES ' },
        { id: 317, countryId: 52, name: ' GUACHUCAL ' },
        { id: 320, countryId: 52, name: ' GUAITARILLA ' },
        { id: 323, countryId: 52, name: ' GUALMATAN ' },
        { id: 352, countryId: 52, name: ' ILES ' },
        { id: 354, countryId: 52, name: ' IMUES ' },
        { id: 356, countryId: 52, name: ' IPIALES ' },
        { id: 378, countryId: 52, name: ' LA CRUZ ' },
        { id: 381, countryId: 52, name: ' LA FLORIDA ' },
        { id: 385, countryId: 52, name: ' LA LLANADA ' },
        { id: 390, countryId: 52, name: ' LA TOLA ' },
        { id: 399, countryId: 52, name: ' LA UNION ' },
        { id: 405, countryId: 52, name: ' LEIVA ' },
        { id: 411, countryId: 52, name: ' LINARES ' },
        { id: 418, countryId: 52, name: ' LOS ANDES ' },
        { id: 427, countryId: 52, name: ' MAGsI ' },
        { id: 435, countryId: 52, name: ' MALLAMA ' },
        { id: 473, countryId: 52, name: ' MOSQUERA ' },
        { id: 480, countryId: 52, name: ' NARIÑO ' },
        { id: 490, countryId: 52, name: ' OLAYA HERRERA ' },
        { id: 506, countryId: 52, name: ' OSPINA ' },
        { id: 520, countryId: 52, name: ' FRANCISCO PIZARRO ' },
        { id: 540, countryId: 52, name: ' POLICARPA ' },
        { id: 560, countryId: 52, name: ' POTOSI ' },
        { id: 565, countryId: 52, name: ' PROVIDENCIA ' },
        { id: 573, countryId: 52, name: ' PUERRES ' },
        { id: 585, countryId: 52, name: ' PUPIALES ' },
        { id: 612, countryId: 52, name: ' RICAURTE ' },
        { id: 621, countryId: 52, name: ' ROBERTO PAYAN ' },
        { id: 678, countryId: 52, name: ' SAMANIEGO ' },
        { id: 683, countryId: 52, name: ' SANDONA ' },
        { id: 685, countryId: 52, name: ' SAN BERNARDO ' },
        { id: 687, countryId: 52, name: ' SAN LORENZO ' },
        { id: 693, countryId: 52, name: ' SAN PABLO ' },
        { id: 694, countryId: 52, name: ' SAN PEDRO DE CARTAGO ' },
        { id: 696, countryId: 52, name: ' SANTA BARBARA ' },
        { id: 699, countryId: 52, name: ' SANTACRUZ ' },
        { id: 720, countryId: 52, name: ' SAPUYES ' },
        { id: 786, countryId: 52, name: ' TAMINANGO ' },
        { id: 788, countryId: 52, name: ' TANGUA ' },
        { id: 835, countryId: 52, name: ' SAN ANDRES DE TUMACO ' },
        { id: 838, countryId: 52, name: ' TUQUERRES ' },
        { id: 885, countryId: 52, name: ' YACUANQUER ' },
        { id: 1, countryId: 54, name: ' CUCUTA ' },
        { id: 3, countryId: 54, name: ' ABREGO ' },
        { id: 51, countryId: 54, name: ' ARBOLEDAS ' },
        { id: 99, countryId: 54, name: ' BOCHALEMA ' },
        { id: 109, countryId: 54, name: ' BUCARASICA ' },
        { id: 125, countryId: 54, name: ' CACOTA ' },
        { id: 128, countryId: 54, name: ' CACHIRA ' },
        { id: 172, countryId: 54, name: ' CHINACOTA ' },
        { id: 174, countryId: 54, name: ' CHITAGA ' },
        { id: 206, countryId: 54, name: ' CONVENCION ' },
        { id: 223, countryId: 54, name: ' CUCUTILLA ' },
        { id: 239, countryId: 54, name: ' DURANIA ' },
        { id: 245, countryId: 54, name: ' EL CARMEN ' },
        { id: 250, countryId: 54, name: ' EL TARRA ' },
        { id: 261, countryId: 54, name: ' EL ZULIA ' },
        { id: 313, countryId: 54, name: ' GRAMALOTE ' },
        { id: 344, countryId: 54, name: ' HACARI ' },
        { id: 347, countryId: 54, name: ' HERRAN ' },
        { id: 377, countryId: 54, name: ' LABATECA ' },
        { id: 385, countryId: 54, name: ' LA ESPERANZA ' },
        { id: 398, countryId: 54, name: ' LA PLAYA ' },
        { id: 405, countryId: 54, name: ' LOS PATIOS ' },
        { id: 418, countryId: 54, name: ' LOURDES ' },
        { id: 480, countryId: 54, name: ' MUTISCUA ' },
        { id: 498, countryId: 54, name: ' OCAÑA ' },
        { id: 518, countryId: 54, name: ' PAMPLONA ' },
        { id: 520, countryId: 54, name: ' PAMPLONITA ' },
        { id: 553, countryId: 54, name: ' PUERTO SANTANDER ' },
        { id: 599, countryId: 54, name: ' RAGONVALIA ' },
        { id: 660, countryId: 54, name: ' SALAZAR ' },
        { id: 670, countryId: 54, name: ' SAN CALIXTO ' },
        { id: 673, countryId: 54, name: ' SAN CAYETANO ' },
        { id: 680, countryId: 54, name: ' SANTIAGO ' },
        { id: 720, countryId: 54, name: ' SARDINATA ' },
        { id: 743, countryId: 54, name: ' SILOS ' },
        { id: 800, countryId: 54, name: ' TEORAMA ' },
        { id: 810, countryId: 54, name: ' TIBU ' },
        { id: 820, countryId: 54, name: ' TOLEDO ' },
        { id: 871, countryId: 54, name: ' VILLA CARO ' },
        { id: 874, countryId: 54, name: ' VILLA DEL ROSARIO ' },
        { id: 1, countryId: 63, name: ' ARMENIA ' },
        { id: 111, countryId: 63, name: ' BUENAVISTA ' },
        { id: 130, countryId: 63, name: ' CALARCA ' },
        { id: 190, countryId: 63, name: ' CIRCASIA ' },
        { id: 212, countryId: 63, name: ' CORDOBA ' },
        { id: 272, countryId: 63, name: ' FILANDIA ' },
        { id: 302, countryId: 63, name: ' GENOVA ' },
        { id: 401, countryId: 63, name: ' LA TEBAIDA ' },
        { id: 470, countryId: 63, name: ' MONTENEGRO ' },
        { id: 548, countryId: 63, name: ' PIJAO ' },
        { id: 594, countryId: 63, name: ' QUIMBAYA ' },
        { id: 690, countryId: 63, name: ' SALENTO ' },
        { id: 1, countryId: 66, name: ' PEREIRA ' },
        { id: 45, countryId: 66, name: ' APIA ' },
        { id: 75, countryId: 66, name: ' BALBOA ' },
        { id: 88, countryId: 66, name: ' BELEN DE UMBRIA ' },
        { id: 170, countryId: 66, name: ' DOSQUEBRADAS ' },
        { id: 318, countryId: 66, name: ' GUATICA ' },
        { id: 383, countryId: 66, name: ' LA CELIA ' },
        { id: 400, countryId: 66, name: ' LA VIRGINIA ' },
        { id: 440, countryId: 66, name: ' MARSELLA ' },
        { id: 456, countryId: 66, name: ' MISTRATO ' },
        { id: 572, countryId: 66, name: ' PUEBLO RICO ' },
        { id: 594, countryId: 66, name: ' QUINCHIA ' },
        { id: 682, countryId: 66, name: ' SANTA ROSA DE CABAL ' },
        { id: 687, countryId: 66, name: ' SANTUARIO ' },
        { id: 1, countryId: 68, name: ' BUCARAMANGA ' },
        { id: 13, countryId: 68, name: ' AGUADA ' },
        { id: 20, countryId: 68, name: ' ALBANIA ' },
        { id: 51, countryId: 68, name: ' ARATOCA ' },
        { id: 77, countryId: 68, name: ' BARBOSA ' },
        { id: 79, countryId: 68, name: ' BARICHARA ' },
        { id: 81, countryId: 68, name: ' BARRANCABERMEJA ' },
        { id: 92, countryId: 68, name: ' BETULIA ' },
        { id: 101, countryId: 68, name: ' BOLIVAR ' },
        { id: 121, countryId: 68, name: ' CABRERA ' },
        { id: 132, countryId: 68, name: ' CALIFORNIA ' },
        { id: 147, countryId: 68, name: ' CAPITANEJO ' },
        { id: 152, countryId: 68, name: ' CARCASI ' },
        { id: 160, countryId: 68, name: ' CEPITA ' },
        { id: 162, countryId: 68, name: ' CERRITO ' },
        { id: 167, countryId: 68, name: ' CHARALA ' },
        { id: 169, countryId: 68, name: ' CHARTA ' },
        { id: 176, countryId: 68, name: ' CHIMA ' },
        { id: 179, countryId: 68, name: ' CHIPATA ' },
        { id: 190, countryId: 68, name: ' CIMITARRA ' },
        { id: 207, countryId: 68, name: ' CONCEPCION ' },
        { id: 209, countryId: 68, name: ' CONFINES ' },
        { id: 211, countryId: 68, name: ' CONTRATACION ' },
        { id: 217, countryId: 68, name: ' COROMORO ' },
        { id: 229, countryId: 68, name: ' CURITI ' },
        { id: 235, countryId: 68, name: ' EL CARMEN DE CHUCURI ' },
        { id: 245, countryId: 68, name: ' EL GUACAMAYO ' },
        { id: 250, countryId: 68, name: ' EL PEÑON ' },
        { id: 255, countryId: 68, name: ' EL PLAYON ' },
        { id: 264, countryId: 68, name: ' ENCINO ' },
        { id: 266, countryId: 68, name: ' ENCISO ' },
        { id: 271, countryId: 68, name: ' FLORIAN ' },
        { id: 276, countryId: 68, name: ' FLORIDABLANCA ' },
        { id: 296, countryId: 68, name: ' GALAN ' },
        { id: 298, countryId: 68, name: ' GAMBITA ' },
        { id: 307, countryId: 68, name: ' GIRON ' },
        { id: 318, countryId: 68, name: ' GUACA ' },
        { id: 320, countryId: 68, name: ' GUADALUPE ' },
        { id: 322, countryId: 68, name: ' GUAPOTA ' },
        { id: 324, countryId: 68, name: ' GUAVATA ' },
        { id: 327, countryId: 68, name: ' GsEPSA ' },
        { id: 344, countryId: 68, name: ' HATO ' },
        { id: 368, countryId: 68, name: ' JESUS MARIA ' },
        { id: 370, countryId: 68, name: ' JORDAN ' },
        { id: 377, countryId: 68, name: ' LA BELLEZA ' },
        { id: 385, countryId: 68, name: ' LANDAZURI ' },
        { id: 397, countryId: 68, name: ' LA PAZ ' },
        { id: 406, countryId: 68, name: ' LEBRIJA ' },
        { id: 418, countryId: 68, name: ' LOS SANTOS ' },
        { id: 425, countryId: 68, name: ' MACARAVITA ' },
        { id: 432, countryId: 68, name: ' MALAGA ' },
        { id: 444, countryId: 68, name: ' MATANZA ' },
        { id: 464, countryId: 68, name: ' MOGOTES ' },
        { id: 468, countryId: 68, name: ' MOLAGAVITA ' },
        { id: 498, countryId: 68, name: ' OCAMONTE ' },
        { id: 500, countryId: 68, name: ' OIBA ' },
        { id: 502, countryId: 68, name: ' ONZAGA ' },
        { id: 522, countryId: 68, name: ' PALMAR ' },
        { id: 524, countryId: 68, name: ' PALMAS DEL SOCORRO ' },
        { id: 533, countryId: 68, name: ' PARAMO ' },
        { id: 547, countryId: 68, name: ' PIEDECUESTA ' },
        { id: 549, countryId: 68, name: ' PINCHOTE ' },
        { id: 572, countryId: 68, name: ' PUENTE NACIONAL ' },
        { id: 573, countryId: 68, name: ' PUERTO PARRA ' },
        { id: 575, countryId: 68, name: ' PUERTO WILCHES ' },
        { id: 615, countryId: 68, name: ' RIONEGRO ' },
        { id: 655, countryId: 68, name: ' SABANA DE TORRES ' },
        { id: 669, countryId: 68, name: ' SAN ANDRES ' },
        { id: 673, countryId: 68, name: ' SAN BENITO ' },
        { id: 679, countryId: 68, name: ' SAN GIL ' },
        { id: 682, countryId: 68, name: ' SAN JOAQUIN ' },
        { id: 684, countryId: 68, name: ' SAN JOSE DE MIRANDA ' },
        { id: 686, countryId: 68, name: ' SAN MIGUEL ' },
        { id: 689, countryId: 68, name: ' SAN VICENTE DE CHUCURI ' },
        { id: 705, countryId: 68, name: ' SANTA BARBARA ' },
        { id: 720, countryId: 68, name: ' SANTA HELENA DEL OPON ' },
        { id: 745, countryId: 68, name: ' SIMACOTA ' },
        { id: 755, countryId: 68, name: ' SOCORRO ' },
        { id: 770, countryId: 68, name: ' SUAITA ' },
        { id: 773, countryId: 68, name: ' SUCRE ' },
        { id: 780, countryId: 68, name: ' SURATA ' },
        { id: 820, countryId: 68, name: ' TONA ' },
        { id: 855, countryId: 68, name: ' VALLE DE SAN JOSE ' },
        { id: 861, countryId: 68, name: ' VELEZ ' },
        { id: 867, countryId: 68, name: ' VETAS ' },
        { id: 872, countryId: 68, name: ' VILLANUEVA ' },
        { id: 895, countryId: 68, name: ' ZAPATOCA ' },
        { id: 1, countryId: 70, name: ' SINCELEJO ' },
        { id: 110, countryId: 70, name: ' BUENAVISTA ' },
        { id: 124, countryId: 70, name: ' CAIMITO ' },
        { id: 204, countryId: 70, name: ' COLOSO ' },
        { id: 215, countryId: 70, name: ' COROZAL ' },
        { id: 221, countryId: 70, name: ' COVEÑAS ' },
        { id: 230, countryId: 70, name: ' CHALAN ' },
        { id: 233, countryId: 70, name: ' EL ROBLE ' },
        { id: 235, countryId: 70, name: ' GALERAS ' },
        { id: 265, countryId: 70, name: ' GUARANDA ' },
        { id: 400, countryId: 70, name: ' LA UNION ' },
        { id: 418, countryId: 70, name: ' LOS PALMITOS ' },
        { id: 429, countryId: 70, name: ' MAJAGUAL ' },
        { id: 473, countryId: 70, name: ' MORROA ' },
        { id: 508, countryId: 70, name: ' OVEJAS ' },
        { id: 523, countryId: 70, name: ' PALMITO ' },
        { id: 670, countryId: 70, name: ' SAMPUES ' },
        { id: 678, countryId: 70, name: ' SAN BENITO ABAD ' },
        { id: 702, countryId: 70, name: ' SAN JUAN DE BETULIA ' },
        { id: 708, countryId: 70, name: ' SAN MARCOS ' },
        { id: 713, countryId: 70, name: ' SAN ONOFRE ' },
        { id: 717, countryId: 70, name: ' SAN PEDRO ' },
        { id: 742, countryId: 70, name: ' SAN LUIS DE SINCE ' },
        { id: 771, countryId: 70, name: ' SUCRE ' },
        { id: 820, countryId: 70, name: ' SANTIAGO DE TOLU ' },
        { id: 823, countryId: 70, name: ' TOLU VIEJO ' },
        { id: 1, countryId: 73, name: ' IBAGUE ' },
        { id: 24, countryId: 73, name: ' ALPUJARRA ' },
        { id: 26, countryId: 73, name: ' ALVARADO ' },
        { id: 30, countryId: 73, name: ' AMBALEMA ' },
        { id: 43, countryId: 73, name: ' ANZOATEGUI ' },
        { id: 55, countryId: 73, name: ' ARMERO ' },
        { id: 67, countryId: 73, name: ' ATACO ' },
        { id: 124, countryId: 73, name: ' CAJAMARCA ' },
        { id: 148, countryId: 73, name: ' CARMEN DE APICALA ' },
        { id: 152, countryId: 73, name: ' CASABIANCA ' },
        { id: 168, countryId: 73, name: ' CHAPARRAL ' },
        { id: 200, countryId: 73, name: ' COELLO ' },
        { id: 217, countryId: 73, name: ' COYAIMA ' },
        { id: 226, countryId: 73, name: ' CUNDAY ' },
        { id: 236, countryId: 73, name: ' DOLORES ' },
        { id: 268, countryId: 73, name: ' ESPINAL ' },
        { id: 270, countryId: 73, name: ' FALAN ' },
        { id: 275, countryId: 73, name: ' FLANDES ' },
        { id: 283, countryId: 73, name: ' FRESNO ' },
        { id: 319, countryId: 73, name: ' GUAMO ' },
        { id: 347, countryId: 73, name: ' HERVEO ' },
        { id: 349, countryId: 73, name: ' HONDA ' },
        { id: 352, countryId: 73, name: ' ICONONZO ' },
        { id: 408, countryId: 73, name: ' LERIDA ' },
        { id: 411, countryId: 73, name: ' LIBANO ' },
        { id: 443, countryId: 73, name: ' MARIQUITA ' },
        { id: 449, countryId: 73, name: ' MELGAR ' },
        { id: 461, countryId: 73, name: ' MURILLO ' },
        { id: 483, countryId: 73, name: ' NATAGAIMA ' },
        { id: 504, countryId: 73, name: ' ORTEGA ' },
        { id: 520, countryId: 73, name: ' PALOCABILDO ' },
        { id: 547, countryId: 73, name: ' PIEDRAS ' },
        { id: 555, countryId: 73, name: ' PLANADAS ' },
        { id: 563, countryId: 73, name: ' PRADO ' },
        { id: 585, countryId: 73, name: ' PURIFICACION ' },
        { id: 616, countryId: 73, name: ' RIOBLANCO ' },
        { id: 622, countryId: 73, name: ' RONCESVALLES ' },
        { id: 624, countryId: 73, name: ' ROVIRA ' },
        { id: 671, countryId: 73, name: ' SALDAÑA ' },
        { id: 675, countryId: 73, name: ' SAN ANTONIO ' },
        { id: 678, countryId: 73, name: ' SAN LUIS ' },
        { id: 686, countryId: 73, name: ' SANTA ISABEL ' },
        { id: 770, countryId: 73, name: ' SUAREZ ' },
        { id: 854, countryId: 73, name: ' VALLE DE SAN JUAN ' },
        { id: 861, countryId: 73, name: ' VENADILLO ' },
        { id: 870, countryId: 73, name: ' VILLAHERMOSA ' },
        { id: 873, countryId: 73, name: ' VILLARRICA ' },
        { id: 1, countryId: 76, name: ' CALI ' },
        { id: 20, countryId: 76, name: ' ALCALA ' },
        { id: 36, countryId: 76, name: ' ANDALUCIA ' },
        { id: 41, countryId: 76, name: ' ANSERMANUEVO ' },
        { id: 54, countryId: 76, name: ' ARGELIA ' },
        { id: 100, countryId: 76, name: ' BOLIVAR ' },
        { id: 109, countryId: 76, name: ' BUENAVENTURA ' },
        { id: 111, countryId: 76, name: ' GUADALAJARA DE BUGA ' },
        { id: 113, countryId: 76, name: ' BUGALAGRANDE ' },
        { id: 122, countryId: 76, name: ' CAICEDONIA ' },
        { id: 126, countryId: 76, name: ' CALIMA ' },
        { id: 130, countryId: 76, name: ' CANDELARIA ' },
        { id: 147, countryId: 76, name: ' CARTAGO ' },
        { id: 233, countryId: 76, name: ' DAGUA ' },
        { id: 243, countryId: 76, name: ' EL AGUILA ' },
        { id: 246, countryId: 76, name: ' EL CAIRO ' },
        { id: 248, countryId: 76, name: ' EL CERRITO ' },
        { id: 250, countryId: 76, name: ' EL DOVIO ' },
        { id: 275, countryId: 76, name: ' FLORIDA ' },
        { id: 306, countryId: 76, name: ' GINEBRA ' },
        { id: 318, countryId: 76, name: ' GUACARI ' },
        { id: 364, countryId: 76, name: ' JAMUNDI ' },
        { id: 377, countryId: 76, name: ' LA CUMBRE ' },
        { id: 400, countryId: 76, name: ' LA UNION ' },
        { id: 403, countryId: 76, name: ' LA VICTORIA ' },
        { id: 497, countryId: 76, name: ' OBANDO ' },
        { id: 520, countryId: 76, name: ' PALMIRA ' },
        { id: 563, countryId: 76, name: ' PRADERA ' },
        { id: 606, countryId: 76, name: ' RESTREPO ' },
        { id: 616, countryId: 76, name: ' RIOFRIO ' },
        { id: 622, countryId: 76, name: ' ROLDANILLO ' },
        { id: 670, countryId: 76, name: ' SAN PEDRO ' },
        { id: 736, countryId: 76, name: ' SEVILLA ' },
        { id: 823, countryId: 76, name: ' TORO ' },
        { id: 828, countryId: 76, name: ' TRUJILLO ' },
        { id: 834, countryId: 76, name: ' TULUA ' },
        { id: 845, countryId: 76, name: ' ULLOA ' },
        { id: 863, countryId: 76, name: ' VERSALLES ' },
        { id: 869, countryId: 76, name: ' VIJES ' },
        { id: 890, countryId: 76, name: ' YOTOCO ' },
        { id: 892, countryId: 76, name: ' YUMBO ' },
        { id: 895, countryId: 76, name: ' ZARZAL ' },
        { id: 1, countryId: 81, name: ' ARAUCA ' },
        { id: 65, countryId: 81, name: ' ARAUQUITA ' },
        { id: 220, countryId: 81, name: ' CRAVO NORTE ' },
        { id: 300, countryId: 81, name: ' FORTUL ' },
        { id: 591, countryId: 81, name: ' PUERTO RONDON ' },
        { id: 736, countryId: 81, name: ' SARAVENA ' },
        { id: 794, countryId: 81, name: ' TAME ' },
        { id: 1, countryId: 85, name: ' YOPAL ' },
        { id: 10, countryId: 85, name: ' AGUAZUL ' },
        { id: 15, countryId: 85, name: ' CHAMEZA ' },
        { id: 125, countryId: 85, name: ' HATO COROZAL ' },
        { id: 136, countryId: 85, name: ' LA SALINA ' },
        { id: 139, countryId: 85, name: ' MANI ' },
        { id: 162, countryId: 85, name: ' MONTERREY ' },
        { id: 225, countryId: 85, name: ' NUNCHIA ' },
        { id: 230, countryId: 85, name: ' OROCUE ' },
        { id: 250, countryId: 85, name: ' PAZ DE ARIPORO ' },
        { id: 263, countryId: 85, name: ' PORE ' },
        { id: 279, countryId: 85, name: ' RECETOR ' },
        { id: 300, countryId: 85, name: ' SABANALARGA ' },
        { id: 315, countryId: 85, name: ' SACAMA ' },
        { id: 325, countryId: 85, name: ' SAN LUIS DE PALENQUE ' },
        { id: 400, countryId: 85, name: ' TAMARA ' },
        { id: 410, countryId: 85, name: ' TAURAMENA ' },
        { id: 430, countryId: 85, name: ' TRINIDAD ' },
        { id: 440, countryId: 85, name: ' VILLANUEVA ' },
        { id: 1, countryId: 86, name: ' MOCOA ' },
        { id: 219, countryId: 86, name: ' COLON ' },
        { id: 320, countryId: 86, name: ' ORITO ' },
        { id: 568, countryId: 86, name: ' PUERTO ASIS ' },
        { id: 569, countryId: 86, name: ' PUERTO CAICEDO ' },
        { id: 571, countryId: 86, name: ' PUERTO GUZMAN ' },
        { id: 573, countryId: 86, name: ' LEGUIZAMO ' },
        { id: 749, countryId: 86, name: ' SIBUNDOY ' },
        { id: 755, countryId: 86, name: ' SAN FRANCISCO ' },
        { id: 757, countryId: 86, name: ' SAN MIGUEL ' },
        { id: 760, countryId: 86, name: ' SANTIAGO ' },
        { id: 865, countryId: 86, name: ' VALLE DEL GUAMUEZ ' },
        { id: 885, countryId: 86, name: ' VILLAGARZON ' },
        { id: 1, countryId: 88, name: ' SAN ANDRES ' },
        { id: 564, countryId: 88, name: ' PROVIDENCIA ' },
        { id: 1, countryId: 91, name: ' LETICIA ' },
        { id: 263, countryId: 91, name: ' EL ENCANTO ' },
        { id: 405, countryId: 91, name: ' LA CHORRERA ' },
        { id: 407, countryId: 91, name: ' LA PEDRERA ' },
        { id: 430, countryId: 91, name: ' LA VICTORIA ' },
        { id: 460, countryId: 91, name: ' MIRITI - PARANA ' },
        { id: 530, countryId: 91, name: ' PUERTO ALEGRIA ' },
        { id: 536, countryId: 91, name: ' PUERTO ARICA ' },
        { id: 540, countryId: 91, name: ' PUERTO NARIÑO ' },
        { id: 669, countryId: 91, name: ' PUERTO SANTANDER ' },
        { id: 798, countryId: 91, name: ' TARAPACA ' },
        { id: 1, countryId: 94, name: ' INIRIDA ' },
        { id: 343, countryId: 94, name: ' BARRANCO MINAS ' },
        { id: 663, countryId: 94, name: ' MAPIRIPANA ' },
        { id: 883, countryId: 94, name: ' SAN FELIPE ' },
        { id: 884, countryId: 94, name: ' PUERTO COLOMBIA ' },
        { id: 885, countryId: 94, name: ' LA GUADALUPE ' },
        { id: 886, countryId: 94, name: ' CACAHUAL ' },
        { id: 887, countryId: 94, name: ' PANA PANA ' },
        { id: 888, countryId: 94, name: ' MORICHAL ' },
        { id: 1, countryId: 95, name: ' SAN JOSE DEL GUAVIARE ' },
        { id: 15, countryId: 95, name: ' CALAMAR ' },
        { id: 25, countryId: 95, name: ' EL RETORNO ' },
        { id: 200, countryId: 95, name: ' MIRAFLORES ' },
        { id: 1, countryId: 97, name: ' MITU ' },
        { id: 161, countryId: 97, name: ' CARURU ' },
        { id: 511, countryId: 97, name: ' PACOA ' },
        { id: 666, countryId: 97, name: ' TARAIRA ' },
        { id: 777, countryId: 97, name: ' PAPUNAUA ' },
        { id: 889, countryId: 97, name: ' YAVARATE ' },
        { id: 1, countryId: 99, name: ' PUERTO CARREÑO ' },
        { id: 524, countryId: 99, name: ' LA PRIMAVERA ' },
        { id: 624, countryId: 99, name: ' SANTA ROSALIA ' },
        { id: 773, countryId: 99, name: ' CUMARIBO ' },
    ];

    getStates(): StateI[] {
        return this.states;
    }

    getCities(): CityI[] {
        return this.cities;
    }

}